# Generated by Django 4.0.4 on 2022-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_descriptions_todo_description_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Description_Box',
        ),
        migrations.AddField(
            model_name='todo',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
